"""
Insurance Claim Fraud Detection — small live demo
----------------------------------------------------
100% synthetic data (see fraud_lib/data.py). No employer data of any kind.
Built to be understood and used without anyone explaining it live.

Repo layout:
  app.py            <- this file, Streamlit UI only
  fraud_lib/data.py  <- synthetic data generation
  fraud_lib/model.py <- model comparison, calibration, cost-sensitive threshold, explainability
  tests/             <- pytest sanity checks on the above
"""
import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

from fraud_lib.data import CLAIM_TYPES, generate_claims
from fraud_lib.model import (
    build_input_row,
    calibration_points,
    local_explanation,
    optimal_threshold,
    train_and_select,
)

st.set_page_config(page_title="Claim Fraud Detection — demo", page_icon="🔎", layout="wide")


@st.cache_data
def get_data():
    return generate_claims()


@st.cache_resource
def get_bundle():
    return train_and_select()


df = get_data()
bundle = get_bundle()
model = bundle.model
feature_columns = bundle.feature_columns

# ----------------------------------------------------------------------------
# Header
# ----------------------------------------------------------------------------
st.title("🔎 Insurance Claim Fraud Detection — small demo")
st.markdown(
    "Self-contained fraud-scoring demo built for a technical exchange. "
    "**All data is synthetic**, generated by `fraud_lib/data.py` — nothing here "
    "comes from any employer or real policyholder. Source code, including the "
    "model-comparison and calibration logic, is in this app's repository."
)
with st.expander("Selected model & validation summary", expanded=False):
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Selected model", bundle.model_name.replace("_", " "))
    c2.metric("Test ROC AUC", f"{bundle.auc:.3f}")
    c3.metric("Brier — before calibration", f"{bundle.brier_uncalibrated:.3f}")
    c4.metric("Brier — after calibration", f"{bundle.brier:.3f}", delta=f"{bundle.brier - bundle.brier_uncalibrated:+.3f}", delta_color="inverse")
    st.caption(
        "Two models (logistic regression, random forest) were compared by 5-fold "
        "cross-validated ROC AUC on the training split before selecting this one. "
        "class_weight='balanced' (needed for the ~8% minority class) reliably makes "
        "probabilities overconfident, so isotonic calibration is applied on top — "
        "the Brier score above shows the measured effect, not just the claim."
    )

tab1, tab2, tab3 = st.tabs(["Score a claim", "Model & data overview", "Scope & what I left out"])

# ---- TAB 1 : score a claim -------------------------------------------------
with tab1:
    st.subheader("Score a new claim")
    col_in, col_out = st.columns([1, 1.2])

    with col_in:
        claim_type = st.selectbox("Claim type", CLAIM_TYPES, index=0)
        claim_amount = st.slider("Claim amount (€)", 100, 30000, 3000, step=100)
        policy_value = st.slider("Policy value (€)", 3000, 30000, 15000, step=500)
        policy_tenure_years = st.slider("Policy tenure (years)", 0.1, 25.0, 3.0, step=0.1)
        prior_claims_count = st.number_input("Prior claims count", 0, 10, 0)
        reported_delay_days = st.slider("Days between incident and report", 0, 60, 2)
        weekend_incident = st.checkbox("Incident occurred on a weekend")
        has_prior_fraud_flag = st.checkbox("Prior fraud flag on file")

        st.markdown("---")
        st.markdown("**Operating threshold — business cost inputs**")
        cost_fp = st.number_input("Cost of a false alarm (analyst review, €)", 10, 1000, 80, step=10)
        cost_fn = st.number_input("Cost of a missed fraud (avg. payout, €)", 500, 20000, 5000, step=100)
        max_review_rate = st.slider("Max share of claims the review team can handle", 0.02, 1.0, 0.15, step=0.01)

    inputs = dict(
        claim_type=claim_type, claim_amount=claim_amount, policy_value=policy_value,
        policy_tenure_years=policy_tenure_years, prior_claims_count=prior_claims_count,
        reported_delay_days=reported_delay_days,
        weekend_incident=int(weekend_incident), has_prior_fraud_flag=int(has_prior_fraud_flag),
    )
    X_new = build_input_row(inputs, feature_columns)
    proba = model.predict_proba(X_new)[0, 1]
    threshold, sweep = optimal_threshold(
        bundle.y_test, bundle.proba_test, cost_fp=cost_fp, cost_fn=cost_fn,
        max_review_rate=max_review_rate,
    )

    with col_out:
        st.metric("Calibrated fraud probability", f"{proba:.1%}")
        st.progress(min(int(proba * 100), 100))
        st.caption(
            f"Operating threshold for this cost ratio and capacity: **{threshold:.2f}** "
            f"(chosen by minimizing expected cost on the held-out test set, "
            f"subject to reviewing at most {max_review_rate:.0%} of claims)."
        )
        if proba >= threshold:
            st.error("Above the operating threshold — would be routed to manual review.")
        else:
            st.success("Below the operating threshold — would be auto-approved in this demo.")

        st.markdown("**Why this score (permutation-importance weighted deviation, not SHAP)**")
        expl = local_explanation(X_new.iloc[0], bundle.train_means, bundle.train_stds, bundle.perm_importance)
        fig, ax = plt.subplots(figsize=(5, 3))
        colors = ["#c0392b" if v > 0 else "#2980b9" for v in expl.values]
        ax.barh(expl.index[::-1], expl.values[::-1], color=colors[::-1])
        ax.set_xlabel("Push toward fraud (red) / away from fraud (blue)")
        st.pyplot(fig)
        st.caption(
            "This is z-scored deviation from the training-set average, weighted by "
            "global permutation importance — a fast, honest approximation. It is "
            "not a game-theoretic (SHAP) attribution; see the Scope tab."
        )

# ---- TAB 2 : model & data overview -----------------------------------------
with tab2:
    st.subheader("Dataset overview")
    c1, c2, c3 = st.columns(3)
    c1.metric("Claims (synthetic)", f"{len(df):,}")
    c2.metric("Fraud rate", f"{df['is_fraud'].mean():.1%}")
    c3.metric("Test-set ROC AUC", f"{bundle.auc:.3f}")

    col1, col2 = st.columns(2)
    with col1:
        st.markdown("**Fraud rate by claim type**")
        fig, ax = plt.subplots(figsize=(5, 3.2))
        rates = df.groupby("claim_type")["is_fraud"].mean().sort_values(ascending=False)
        ax.bar(rates.index, rates.values, color="#2c4a7c")
        ax.set_ylabel("Fraud rate")
        plt.xticks(rotation=30, ha="right")
        st.pyplot(fig)
    with col2:
        st.markdown("**Claim amount distribution, fraud vs. not**")
        fig, ax = plt.subplots(figsize=(5, 3.2))
        ax.hist(df.loc[df.is_fraud == 0, "claim_amount"], bins=40, alpha=0.6, label="not fraud", color="#2980b9")
        ax.hist(df.loc[df.is_fraud == 1, "claim_amount"], bins=40, alpha=0.6, label="fraud", color="#c0392b")
        ax.set_xlabel("Claim amount (€)")
        ax.legend()
        st.pyplot(fig)

    st.subheader("Model comparison (5-fold cross-validated ROC AUC, training split)")
    cmp_df = pd.DataFrame(bundle.candidate_scores).T
    cmp_df.index.name = "model"
    st.dataframe(cmp_df.style.format({"mean_auc": "{:.3f}", "std_auc": "{:.3f}"}), use_container_width=True)
    st.caption(f"Selected: **{bundle.model_name.replace('_', ' ')}** (highest mean CV AUC).")

    st.subheader("Calibration — before vs. after isotonic calibration")
    col5, col6 = st.columns(2)
    with col5:
        mp_before, fp_before = calibration_points(bundle.y_test, bundle.proba_test_uncalibrated)
        mp_after, fp_after = calibration_points(bundle.y_test, bundle.proba_test)
        fig, ax = plt.subplots(figsize=(5, 4.2))
        ax.plot([0, 1], [0, 1], "--", color="grey", label="perfectly calibrated")
        ax.plot(mp_before, fp_before, "o-", color="#c0392b", label=f"before (Brier {bundle.brier_uncalibrated:.3f})")
        ax.plot(mp_after, fp_after, "o-", color="#27ae60", label=f"after (Brier {bundle.brier:.3f})")
        ax.set_xlabel("Mean predicted probability (per bin)")
        ax.set_ylabel("Observed fraud rate (per bin)")
        ax.legend(fontsize=8)
        st.pyplot(fig)
    with col6:
        st.markdown(
            "`class_weight=\"balanced\"` compensates for the ~8% minority class during "
            "training, but it systematically pushes predicted probabilities away from "
            "their true frequencies — the red curve sits well below the diagonal at "
            "high scores, meaning a claim scored 80% fraudulent was, in this test set, "
            "fraudulent far less than 80% of the time.\n\n"
            "Isotonic calibration (`CalibratedClassifierCV`, fit on the training split "
            "only, evaluated on the untouched test split) brings the curve back toward "
            "the diagonal and cuts the Brier score roughly threefold. This matters "
            "operationally: the cost-based threshold in the 'Score a claim' tab is only "
            "trustworthy if the probabilities feeding it are honest."
        )

    st.subheader("Cost-based threshold sweep")
    fig, ax = plt.subplots(figsize=(8, 3.2))
    ax.plot(sweep["threshold"], sweep["expected_cost"], color="#2c4a7c")
    ax.axvline(threshold, color="#c0392b", linestyle="--", label=f"selected threshold = {threshold:.2f}")
    ax.set_xlabel("Threshold")
    ax.set_ylabel("Expected cost on test set (€)")
    ax.legend()
    st.pyplot(fig)
    st.caption(
        "Expected cost = (false positives × cost of a false alarm) + (false negatives × "
        "cost of a missed fraud), computed on the held-out test set, subject to the "
        "review-capacity constraint set in the sidebar. Change the cost inputs in the "
        "'Score a claim' tab and this curve — and the selected threshold — move with them."
    )

    st.subheader("Global feature importance (permutation, test set)")
    fig, ax = plt.subplots(figsize=(8, 3.5))
    imp = bundle.perm_importance.sort_values()
    ax.barh(imp.index, imp.values, color="#27ae60")
    ax.set_xlabel("Mean drop in ROC AUC when the feature is shuffled")
    st.pyplot(fig)
    st.caption(
        "Permutation importance rather than the random forest's built-in impurity "
        "importance (or logistic regression coefficients directly): it is model-agnostic "
        "and measured on the held-out test set, so it reflects generalization rather than "
        "training-set fit."
    )

# ---- TAB 3 : scope -----------------------------------------------------
with tab3:
    st.subheader("What this demo does and does not do")
    st.markdown(
        """
Deliberately small, single scope, built over a few evenings. What's actually
in here: two compared models selected by cross-validated AUC, isotonic
probability calibration (measured, not assumed), a cost- and
capacity-constrained operating threshold instead of a bare 0.5 cutoff, and
model-agnostic permutation importance instead of raw impurity importance.

Left out on purpose:

- **No real data.** Everything is generated by a hand-written logistic rule with
  noise (see `fraud_lib/data.py`). It is realistic enough to be learnable and
  discussable, not a claim about real fraud patterns at any company.
- **No temporal validation.** The train/test split is random, not time-based —
  a real fraud model needs validation on *future* claims relative to training,
  to catch drift. Doing this properly needs a time axis that a one-shot
  synthetic dataset doesn't really have.
- **No SHAP / game-theoretic explainability.** The "why" panel is an
  importance-weighted deviation from the training mean — good enough to
  reason about a single claim in a demo, not for a production explanation
  shown to a client or auditor.
- **No monitoring, no auth, no logging, no persistence.** Stateless scoring
  demo, not a deployable production service.
- **No resampling strategy beyond `class_weight="balanced"`.** No SMOTE, no
  systematic comparison against resampling approaches.
- **No hyperparameter search.** Model hyperparameters are reasonable
  defaults, not tuned by grid/random/Bayesian search.

Happy to talk through how each of these would actually be tackled in production.
        """
    )

st.caption("Source: see this app's GitHub repository (fraud_lib/ for logic, tests/ for sanity checks).")
