"""Synthetic insurance-claims data generator.

Every value in the resulting dataset is generated by the logistic rule
below, seeded for reproducibility. Nothing here comes from any real
policyholder, claim, or employer dataset.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

CLAIM_TYPES = ["water_damage", "fire", "theft", "glass_breakage", "storm"]
CLAIM_TYPE_PROBS = [0.35, 0.10, 0.20, 0.15, 0.20]
BASE_AMOUNT = {"water_damage": 2200, "fire": 9000, "theft": 1800, "glass_breakage": 500, "storm": 3500}

FEATURE_COLUMNS_BASE = [
    "claim_amount", "policy_value", "claim_to_policy_ratio", "policy_tenure_years",
    "prior_claims_count", "reported_delay_days", "weekend_incident", "has_prior_fraud_flag",
]


def generate_claims(n: int = 4000, seed: int = 42) -> pd.DataFrame:
    """Generate a synthetic insurance-claims dataset with a fraud label.

    The fraud label is drawn from a logistic model of interpretable "red
    flag" signals plus noise, so the problem is learnable but not trivially
    separable (this is checked in tests/test_data.py).
    """
    rng = np.random.default_rng(seed)
    claim_type = rng.choice(CLAIM_TYPES, size=n, p=CLAIM_TYPE_PROBS)
    policy_tenure_years = np.round(rng.exponential(scale=4.0, size=n), 1).clip(0.1, 25)
    prior_claims_count = rng.poisson(lam=0.6, size=n)
    reported_delay_days = rng.exponential(scale=3.0, size=n).clip(0, 60)
    weekend_incident = rng.integers(0, 2, size=n)
    has_prior_fraud_flag = rng.choice([0, 1], size=n, p=[0.95, 0.05])

    claim_amount = np.array([rng.gamma(shape=2.0, scale=BASE_AMOUNT[t] / 2.0) for t in claim_type])
    policy_value = rng.normal(loc=15000, scale=4000, size=n).clip(3000, None)
    claim_to_policy_ratio = claim_amount / policy_value

    z = (
        -4.2
        + 2.3 * (claim_to_policy_ratio > 0.5)
        + 0.55 * np.log1p(reported_delay_days)
        + 1.8 * has_prior_fraud_flag
        + 0.35 * (policy_tenure_years < 0.5)
        + 0.4 * (prior_claims_count >= 2)
        + 0.25 * weekend_incident
        + 0.6 * (claim_amount > np.quantile(claim_amount, 0.9))
        + rng.normal(0, 0.6, size=n)
    )
    fraud_proba = 1 / (1 + np.exp(-z))
    is_fraud = rng.binomial(1, fraud_proba)

    return pd.DataFrame({
        "claim_type": claim_type,
        "claim_amount": np.round(claim_amount, 2),
        "policy_value": np.round(policy_value, 2),
        "claim_to_policy_ratio": np.round(claim_to_policy_ratio, 3),
        "policy_tenure_years": policy_tenure_years,
        "prior_claims_count": prior_claims_count,
        "reported_delay_days": np.round(reported_delay_days, 1),
        "weekend_incident": weekend_incident,
        "has_prior_fraud_flag": has_prior_fraud_flag,
        "is_fraud": is_fraud,
    })


def to_model_matrix(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.Series]:
    """One-hot encode claim_type and split features/target."""
    X = pd.get_dummies(df.drop(columns=["is_fraud"]), columns=["claim_type"])
    y = df["is_fraud"]
    return X, y
